import Foundation

/// Returns the string for `key` in the current UI language (English fallback).
func L(_ key: String) -> String {
    L10n.tables[L10n.current]?[key] ?? L10n.tables["en"]?[key] ?? key
}

/// Formatted variant: `L("hud.rec", 0, 7)`.
func L(_ key: String, _ args: CVarArg...) -> String {
    String(format: L(key), arguments: args)
}

enum L10n {
    struct Language {
        let code: String
        let name: String
    }

    static let languages: [Language] = [
        Language(code: "en", name: "English"),
        Language(code: "ru", name: "Русский"),
        Language(code: "es", name: "Español"),
        Language(code: "de", name: "Deutsch"),
        Language(code: "fr", name: "Français"),
        Language(code: "zh", name: "简体中文"),
    ]

    static var current: String {
        get {
            if let stored = UserDefaults.standard.string(forKey: "uiLanguage"), tables[stored] != nil {
                return stored
            }
            return systemDefault()
        }
        set { UserDefaults.standard.set(newValue, forKey: "uiLanguage") }
    }

    static var hasStoredChoice: Bool {
        UserDefaults.standard.string(forKey: "uiLanguage") != nil
    }

    static func systemDefault() -> String {
        for preferred in Locale.preferredLanguages {
            let code = String(preferred.prefix(2))
            if tables[code] != nil { return code }
        }
        return "en"
    }

    static let tables: [String: [String: String]] = [
        "en": [
            "status.hold": "WhisperKey — hold %@",
            "status.ready": "WhisperKey — ready (%@)",
            "status.rec": "Recording… %@",
            "status.rec.hold": "Recording… %@ — release to finish",
            "status.processing": "Transcribing…",
            "warn.rightcmd": "⚠️ Right ⌘ inactive — Accessibility permission missing",
            "menu.axSettings": "Open Accessibility settings…",
            "menu.record": "Start recording",
            "menu.finish": "Done — transcribe and paste",
            "menu.cancel": "Cancel (Esc)",
            "menu.copy": "Copy: “%@”",
            "menu.engine": "Recognition engine",
            "menu.model": "Local model",
            "menu.speechLang": "Speech language",
            "menu.hotkey": "Hotkey",
            "menu.mode": "Recording mode",
            "mode.hold": "Hold the key (push-to-talk)",
            "mode.toggle": "Press to start, press again to stop",
            "menu.autopaste": "Auto-paste into active field",
            "menu.sounds": "Sound feedback",
            "menu.modelsFolder": "Open models folder",
            "menu.login": "Launch at login",
            "menu.quit": "Quit",
            "menu.uiLang": "Interface language",
            "models.none": "No models installed",
            "models.download": "Download:",
            "apikey.item": "%@ API key…",
            "apikey.saved": " (saved)",
            "speech.auto": "Auto-detect",
            "speech.ru": "Russian",
            "speech.en": "English",
            "key.space": "Space",
            "key.rightcmd": "Right ⌘",
            "engine.local": "Local (whisper.cpp)",
            "tag.fast": "fast",
            "tag.accurate": "more accurate",
            "tag.veryfast": "very fast",
            "tag.fastacc": "fast and accurate",
            "tag.faster": "faster",
            "tag.top": "top accuracy",
            "tag.cheap": "cheap",
            "model.recommended": "recommended",
            "model.best": "max quality",
            "unit.mb": "MB",
            "unit.gb": "GB",
            "hud.preparing": "Starting the mic…",
            "hud.rec": "Recording… %d:%02d",
            "hud.processing": "Transcribing…",
            "hud.processingVia": "Transcribing (%@)…",
            "hud.done": "Done — text in clipboard",
            "hud.fallback": "Done (local — cloud unavailable)",
            "hud.empty": "No speech recognized",
            "hud.fail": "Transcription failed",
            "alert.noModel": "No model",
            "alert.noModel.text": "Download a recognition model: menu → Local model → Download.",
            "alert.noCli": "whisper-cli not found",
            "alert.noCli.text": "Install the recognition engine:\nbrew install whisper-cpp",
            "alert.noMic": "No microphone access",
            "alert.noMic.text": "Allow access: System Settings → Privacy & Security → Microphone → WhisperKey.",
            "alert.recFail": "Could not start recording",
            "alert.trFail": "Transcription failed",
            "alert.loginFail": "Could not change the login item",
            "alert.axTitle": "Right ⌘ needs a permission",
            "alert.axText": "To react to the right Command key, grant WhisperKey the Accessibility permission:\nSystem Settings → Privacy & Security → Accessibility.\n\nThen pick “Right ⌘” in the menu again or restart WhisperKey.",
            "apikey.title": "%@ API key",
            "apikey.replace": "A key is already saved. Enter a new one to replace it.",
            "apikey.info": "Paste your %@ API key. It is stored in the app's settings file (readable only by your macOS user) and used only for requests to %@.",
            "btn.save": "Save",
            "btn.cancel": "Cancel",
            "edit.title": "Edit",
            "edit.undo": "Undo",
            "edit.redo": "Redo",
            "edit.cut": "Cut",
            "edit.copy": "Copy",
            "edit.paste": "Paste",
            "edit.all": "Select All",
            "err.noInput": "Microphone unavailable (no input device or no permission).",
            "err.converter": "Failed to set up audio conversion.",
            "err.noCli": "whisper-cli not found. Install it: brew install whisper-cpp",
            "err.tr": "Transcription error: %@",
            "err.http": "The service returned error %d: %@",
            "err.net": "Network unavailable: %@",
            "err.empty": "The service returned an empty response.",
            "err.large": "The recording is too long for Gemini (limit ~7 minutes).",
            "err.nolocal": "no local model",
            "firstrun.title": "Welcome to WhisperKey",
            "firstrun.text": "Choose the interface language.\nYou can change it anytime in the menu.",
            "btn.continue": "Continue",
        ],
        "ru": [
            "status.hold": "WhisperKey — удерживайте %@",
            "status.ready": "WhisperKey — готов (%@)",
            "status.rec": "Запись… %@",
            "status.rec.hold": "Запись… %@ — отпустите клавишу",
            "status.processing": "Распознаю…",
            "warn.rightcmd": "⚠️ Правый ⌘ не работает — нет «Универсального доступа»",
            "menu.axSettings": "Открыть настройки Универсального доступа…",
            "menu.record": "Начать запись",
            "menu.finish": "Готово — распознать и вставить",
            "menu.cancel": "Отменить (Esc)",
            "menu.copy": "Скопировать: «%@»",
            "menu.engine": "Распознавание",
            "menu.model": "Локальная модель",
            "menu.speechLang": "Язык речи",
            "menu.hotkey": "Горячая клавиша",
            "menu.mode": "Режим записи",
            "mode.hold": "Удерживать клавишу (push-to-talk)",
            "mode.toggle": "Нажать — начать, нажать — закончить",
            "menu.autopaste": "Автовставка в активное поле",
            "menu.sounds": "Звуковые сигналы",
            "menu.modelsFolder": "Открыть папку моделей",
            "menu.login": "Запускать при входе",
            "menu.quit": "Выйти",
            "menu.uiLang": "Язык интерфейса",
            "models.none": "Нет установленных моделей",
            "models.download": "Скачать:",
            "apikey.item": "API-ключ %@…",
            "apikey.saved": " (сохранён)",
            "speech.auto": "Определять автоматически",
            "speech.ru": "Русский",
            "speech.en": "Английский",
            "key.space": "Пробел",
            "key.rightcmd": "Правый ⌘",
            "engine.local": "Локально (whisper.cpp)",
            "tag.fast": "быстро",
            "tag.accurate": "точнее",
            "tag.veryfast": "очень быстро",
            "tag.fastacc": "быстро и точно",
            "tag.faster": "быстрее",
            "tag.top": "топ точности",
            "tag.cheap": "дёшево",
            "model.recommended": "рекомендуется",
            "model.best": "максимум качества",
            "unit.mb": "МБ",
            "unit.gb": "ГБ",
            "hud.preparing": "Включаю микрофон…",
            "hud.rec": "Запись… %d:%02d",
            "hud.processing": "Распознаю…",
            "hud.processingVia": "Распознаю (%@)…",
            "hud.done": "Готово — текст в буфере",
            "hud.fallback": "Готово (локально — облако недоступно)",
            "hud.empty": "Ничего не распозналось",
            "hud.fail": "Ошибка распознавания",
            "alert.noModel": "Нет модели",
            "alert.noModel.text": "Скачайте модель распознавания: меню → Локальная модель → Скачать.",
            "alert.noCli": "Не найден whisper-cli",
            "alert.noCli.text": "Установите движок распознавания:\nbrew install whisper-cpp",
            "alert.noMic": "Нет доступа к микрофону",
            "alert.noMic.text": "Разрешите доступ: Настройки системы → Конфиденциальность и безопасность → Микрофон → WhisperKey.",
            "alert.recFail": "Не удалось начать запись",
            "alert.trFail": "Распознавание не удалось",
            "alert.loginFail": "Не удалось изменить автозапуск",
            "alert.axTitle": "Правому ⌘ нужно разрешение",
            "alert.axText": "Чтобы реагировать на правый Command, дайте WhisperKey разрешение «Универсальный доступ»:\nНастройки системы → Конфиденциальность и безопасность → Универсальный доступ.\n\nПосле включения выберите «Правый ⌘» в меню ещё раз или перезапустите WhisperKey.",
            "apikey.title": "API-ключ %@",
            "apikey.replace": "Ключ уже сохранён. Введите новый, чтобы заменить его.",
            "apikey.info": "Вставьте ваш API-ключ %@. Он сохранится в настройках приложения (файл доступен только вашему пользователю) и используется только для запросов к %@.",
            "btn.save": "Сохранить",
            "btn.cancel": "Отмена",
            "edit.title": "Правка",
            "edit.undo": "Отменить",
            "edit.redo": "Повторить",
            "edit.cut": "Вырезать",
            "edit.copy": "Скопировать",
            "edit.paste": "Вставить",
            "edit.all": "Выбрать всё",
            "err.noInput": "Микрофон недоступен (нет входного устройства или нет разрешения).",
            "err.converter": "Не удалось настроить конвертацию аудио.",
            "err.noCli": "Не найден whisper-cli. Установите его: brew install whisper-cpp",
            "err.tr": "Ошибка распознавания: %@",
            "err.http": "Сервис ответил ошибкой %d: %@",
            "err.net": "Сеть недоступна: %@",
            "err.empty": "Сервис вернул пустой ответ.",
            "err.large": "Запись слишком длинная для Gemini (лимит ~7 минут).",
            "err.nolocal": "нет локальной модели",
            "firstrun.title": "Добро пожаловать в WhisperKey",
            "firstrun.text": "Выберите язык интерфейса.\nЕго можно поменять в меню в любой момент.",
            "btn.continue": "Продолжить",
        ],
        "es": [
            "status.hold": "WhisperKey — mantén %@",
            "status.ready": "WhisperKey — listo (%@)",
            "status.rec": "Grabando… %@",
            "status.rec.hold": "Grabando… %@ — suelta para terminar",
            "status.processing": "Transcribiendo…",
            "warn.rightcmd": "⚠️ ⌘ derecha inactiva — falta permiso de Accesibilidad",
            "menu.axSettings": "Abrir ajustes de Accesibilidad…",
            "menu.record": "Iniciar grabación",
            "menu.finish": "Listo — transcribir y pegar",
            "menu.cancel": "Cancelar (Esc)",
            "menu.copy": "Copiar: «%@»",
            "menu.engine": "Motor de reconocimiento",
            "menu.model": "Modelo local",
            "menu.speechLang": "Idioma del habla",
            "menu.hotkey": "Atajo de teclado",
            "menu.mode": "Modo de grabación",
            "mode.hold": "Mantener la tecla (pulsar para hablar)",
            "mode.toggle": "Pulsa para empezar, pulsa para terminar",
            "menu.autopaste": "Pegado automático en el campo activo",
            "menu.sounds": "Sonidos",
            "menu.modelsFolder": "Abrir carpeta de modelos",
            "menu.login": "Abrir al iniciar sesión",
            "menu.quit": "Salir",
            "menu.uiLang": "Idioma de la interfaz",
            "models.none": "No hay modelos instalados",
            "models.download": "Descargar:",
            "apikey.item": "Clave API de %@…",
            "apikey.saved": " (guardada)",
            "speech.auto": "Detección automática",
            "speech.ru": "Ruso",
            "speech.en": "Inglés",
            "key.space": "Espacio",
            "key.rightcmd": "⌘ derecha",
            "engine.local": "Local (whisper.cpp)",
            "tag.fast": "rápido",
            "tag.accurate": "más preciso",
            "tag.veryfast": "muy rápido",
            "tag.fastacc": "rápido y preciso",
            "tag.faster": "más rápido",
            "tag.top": "máxima precisión",
            "tag.cheap": "económico",
            "model.recommended": "recomendado",
            "model.best": "máxima calidad",
            "unit.mb": "MB",
            "unit.gb": "GB",
            "hud.preparing": "Activando el micrófono…",
            "hud.rec": "Grabando… %d:%02d",
            "hud.processing": "Transcribiendo…",
            "hud.processingVia": "Transcribiendo (%@)…",
            "hud.done": "Listo — texto en el portapapeles",
            "hud.fallback": "Listo (local — nube no disponible)",
            "hud.empty": "No se reconoció nada",
            "hud.fail": "Error de transcripción",
            "alert.noModel": "No hay modelo",
            "alert.noModel.text": "Descarga un modelo: menú → Modelo local → Descargar.",
            "alert.noCli": "No se encontró whisper-cli",
            "alert.noCli.text": "Instala el motor de reconocimiento:\nbrew install whisper-cpp",
            "alert.noMic": "Sin acceso al micrófono",
            "alert.noMic.text": "Permite el acceso: Ajustes del Sistema → Privacidad y seguridad → Micrófono → WhisperKey.",
            "alert.recFail": "No se pudo iniciar la grabación",
            "alert.trFail": "La transcripción falló",
            "alert.loginFail": "No se pudo cambiar el inicio automático",
            "alert.axTitle": "⌘ derecha necesita un permiso",
            "alert.axText": "Para reaccionar a la tecla Comando derecha, concede a WhisperKey el permiso de Accesibilidad:\nAjustes del Sistema → Privacidad y seguridad → Accesibilidad.\n\nLuego vuelve a elegir «⌘ derecha» en el menú o reinicia WhisperKey.",
            "apikey.title": "Clave API de %@",
            "apikey.replace": "Ya hay una clave guardada. Introduce una nueva para reemplazarla.",
            "apikey.info": "Pega tu clave API de %@. Se guarda en el archivo de ajustes de la app (legible solo por tu usuario) y se usa solo para las solicitudes a %@.",
            "btn.save": "Guardar",
            "btn.cancel": "Cancelar",
            "edit.title": "Edición",
            "edit.undo": "Deshacer",
            "edit.redo": "Rehacer",
            "edit.cut": "Cortar",
            "edit.copy": "Copiar",
            "edit.paste": "Pegar",
            "edit.all": "Seleccionar todo",
            "err.noInput": "Micrófono no disponible (sin dispositivo de entrada o sin permiso).",
            "err.converter": "No se pudo configurar la conversión de audio.",
            "err.noCli": "No se encontró whisper-cli. Instálalo: brew install whisper-cpp",
            "err.tr": "Error de reconocimiento: %@",
            "err.http": "El servicio devolvió el error %d: %@",
            "err.net": "Red no disponible: %@",
            "err.empty": "El servicio devolvió una respuesta vacía.",
            "err.large": "La grabación es demasiado larga para Gemini (límite ~7 minutos).",
            "err.nolocal": "no hay modelo local",
            "firstrun.title": "Bienvenido a WhisperKey",
            "firstrun.text": "Elige el idioma de la interfaz.\nPuedes cambiarlo en el menú cuando quieras.",
            "btn.continue": "Continuar",
        ],
        "de": [
            "status.hold": "WhisperKey — %@ gedrückt halten",
            "status.ready": "WhisperKey — bereit (%@)",
            "status.rec": "Aufnahme… %@",
            "status.rec.hold": "Aufnahme… %@ — zum Beenden loslassen",
            "status.processing": "Transkribiere…",
            "warn.rightcmd": "⚠️ Rechte ⌘ inaktiv — Bedienungshilfen-Berechtigung fehlt",
            "menu.axSettings": "Bedienungshilfen-Einstellungen öffnen…",
            "menu.record": "Aufnahme starten",
            "menu.finish": "Fertig — transkribieren und einfügen",
            "menu.cancel": "Abbrechen (Esc)",
            "menu.copy": "Kopieren: „%@“",
            "menu.engine": "Erkennungs-Engine",
            "menu.model": "Lokales Modell",
            "menu.speechLang": "Sprache der Aufnahme",
            "menu.hotkey": "Tastenkürzel",
            "menu.mode": "Aufnahmemodus",
            "mode.hold": "Taste halten (Push-to-Talk)",
            "mode.toggle": "Drücken zum Starten, erneut zum Beenden",
            "menu.autopaste": "Automatisch ins aktive Feld einfügen",
            "menu.sounds": "Töne",
            "menu.modelsFolder": "Modellordner öffnen",
            "menu.login": "Beim Anmelden starten",
            "menu.quit": "Beenden",
            "menu.uiLang": "Sprache der Oberfläche",
            "models.none": "Keine Modelle installiert",
            "models.download": "Herunterladen:",
            "apikey.item": "%@-API-Schlüssel…",
            "apikey.saved": " (gespeichert)",
            "speech.auto": "Automatisch erkennen",
            "speech.ru": "Russisch",
            "speech.en": "Englisch",
            "key.space": "Leertaste",
            "key.rightcmd": "Rechte ⌘",
            "engine.local": "Lokal (whisper.cpp)",
            "tag.fast": "schnell",
            "tag.accurate": "genauer",
            "tag.veryfast": "sehr schnell",
            "tag.fastacc": "schnell und genau",
            "tag.faster": "schneller",
            "tag.top": "Top-Genauigkeit",
            "tag.cheap": "günstig",
            "model.recommended": "empfohlen",
            "model.best": "beste Qualität",
            "unit.mb": "MB",
            "unit.gb": "GB",
            "hud.preparing": "Mikrofon wird gestartet…",
            "hud.rec": "Aufnahme… %d:%02d",
            "hud.processing": "Transkribiere…",
            "hud.processingVia": "Transkribiere (%@)…",
            "hud.done": "Fertig — Text in der Zwischenablage",
            "hud.fallback": "Fertig (lokal — Cloud nicht erreichbar)",
            "hud.empty": "Nichts erkannt",
            "hud.fail": "Transkription fehlgeschlagen",
            "alert.noModel": "Kein Modell",
            "alert.noModel.text": "Lade ein Modell herunter: Menü → Lokales Modell → Herunterladen.",
            "alert.noCli": "whisper-cli nicht gefunden",
            "alert.noCli.text": "Engine installieren:\nbrew install whisper-cpp",
            "alert.noMic": "Kein Mikrofonzugriff",
            "alert.noMic.text": "Zugriff erlauben: Systemeinstellungen → Datenschutz & Sicherheit → Mikrofon → WhisperKey.",
            "alert.recFail": "Aufnahme konnte nicht gestartet werden",
            "alert.trFail": "Transkription fehlgeschlagen",
            "alert.loginFail": "Autostart konnte nicht geändert werden",
            "alert.axTitle": "Rechte ⌘ braucht eine Berechtigung",
            "alert.axText": "Damit WhisperKey auf die rechte Command-Taste reagieren kann, erteile die Bedienungshilfen-Berechtigung:\nSystemeinstellungen → Datenschutz & Sicherheit → Bedienungshilfen.\n\nWähle danach „Rechte ⌘“ erneut im Menü oder starte WhisperKey neu.",
            "apikey.title": "%@-API-Schlüssel",
            "apikey.replace": "Es ist bereits ein Schlüssel gespeichert. Gib einen neuen ein, um ihn zu ersetzen.",
            "apikey.info": "Füge deinen %@-API-Schlüssel ein. Er wird in der Einstellungsdatei der App gespeichert (nur für deinen Benutzer lesbar) und nur für Anfragen an %@ verwendet.",
            "btn.save": "Sichern",
            "btn.cancel": "Abbrechen",
            "edit.title": "Bearbeiten",
            "edit.undo": "Widerrufen",
            "edit.redo": "Wiederholen",
            "edit.cut": "Ausschneiden",
            "edit.copy": "Kopieren",
            "edit.paste": "Einfügen",
            "edit.all": "Alles auswählen",
            "err.noInput": "Mikrofon nicht verfügbar (kein Eingabegerät oder keine Berechtigung).",
            "err.converter": "Audio-Konvertierung konnte nicht eingerichtet werden.",
            "err.noCli": "whisper-cli nicht gefunden. Installieren: brew install whisper-cpp",
            "err.tr": "Erkennungsfehler: %@",
            "err.http": "Der Dienst meldete Fehler %d: %@",
            "err.net": "Netzwerk nicht verfügbar: %@",
            "err.empty": "Der Dienst lieferte eine leere Antwort.",
            "err.large": "Die Aufnahme ist zu lang für Gemini (Limit ~7 Minuten).",
            "err.nolocal": "kein lokales Modell",
            "firstrun.title": "Willkommen bei WhisperKey",
            "firstrun.text": "Wähle die Sprache der Oberfläche.\nDu kannst sie jederzeit im Menü ändern.",
            "btn.continue": "Weiter",
        ],
        "fr": [
            "status.hold": "WhisperKey — maintenez %@",
            "status.ready": "WhisperKey — prêt (%@)",
            "status.rec": "Enregistrement… %@",
            "status.rec.hold": "Enregistrement… %@ — relâchez pour terminer",
            "status.processing": "Transcription…",
            "warn.rightcmd": "⚠️ ⌘ droite inactive — autorisation d'accessibilité manquante",
            "menu.axSettings": "Ouvrir les réglages d'accessibilité…",
            "menu.record": "Démarrer l'enregistrement",
            "menu.finish": "Terminé — transcrire et coller",
            "menu.cancel": "Annuler (Échap)",
            "menu.copy": "Copier : « %@ »",
            "menu.engine": "Moteur de reconnaissance",
            "menu.model": "Modèle local",
            "menu.speechLang": "Langue de la parole",
            "menu.hotkey": "Raccourci clavier",
            "menu.mode": "Mode d'enregistrement",
            "mode.hold": "Maintenir la touche (appuyer-pour-parler)",
            "mode.toggle": "Appuyer pour démarrer, appuyer pour terminer",
            "menu.autopaste": "Collage automatique dans le champ actif",
            "menu.sounds": "Sons",
            "menu.modelsFolder": "Ouvrir le dossier des modèles",
            "menu.login": "Lancer à l'ouverture de session",
            "menu.quit": "Quitter",
            "menu.uiLang": "Langue de l'interface",
            "models.none": "Aucun modèle installé",
            "models.download": "Télécharger :",
            "apikey.item": "Clé API %@…",
            "apikey.saved": " (enregistrée)",
            "speech.auto": "Détection automatique",
            "speech.ru": "Russe",
            "speech.en": "Anglais",
            "key.space": "Espace",
            "key.rightcmd": "⌘ droite",
            "engine.local": "Local (whisper.cpp)",
            "tag.fast": "rapide",
            "tag.accurate": "plus précis",
            "tag.veryfast": "très rapide",
            "tag.fastacc": "rapide et précis",
            "tag.faster": "plus rapide",
            "tag.top": "précision maximale",
            "tag.cheap": "économique",
            "model.recommended": "recommandé",
            "model.best": "qualité maximale",
            "unit.mb": "Mo",
            "unit.gb": "Go",
            "hud.preparing": "Activation du micro…",
            "hud.rec": "Enregistrement… %d:%02d",
            "hud.processing": "Transcription…",
            "hud.processingVia": "Transcription (%@)…",
            "hud.done": "Terminé — texte dans le presse-papiers",
            "hud.fallback": "Terminé (local — cloud indisponible)",
            "hud.empty": "Rien n'a été reconnu",
            "hud.fail": "Échec de la transcription",
            "alert.noModel": "Aucun modèle",
            "alert.noModel.text": "Téléchargez un modèle : menu → Modèle local → Télécharger.",
            "alert.noCli": "whisper-cli introuvable",
            "alert.noCli.text": "Installez le moteur de reconnaissance :\nbrew install whisper-cpp",
            "alert.noMic": "Pas d'accès au micro",
            "alert.noMic.text": "Autorisez l'accès : Réglages Système → Confidentialité et sécurité → Micro → WhisperKey.",
            "alert.recFail": "Impossible de démarrer l'enregistrement",
            "alert.trFail": "Échec de la transcription",
            "alert.loginFail": "Impossible de modifier le lancement automatique",
            "alert.axTitle": "⌘ droite nécessite une autorisation",
            "alert.axText": "Pour réagir à la touche Commande droite, accordez à WhisperKey l'autorisation d'accessibilité :\nRéglages Système → Confidentialité et sécurité → Accessibilité.\n\nEnsuite, choisissez à nouveau « ⌘ droite » dans le menu ou relancez WhisperKey.",
            "apikey.title": "Clé API %@",
            "apikey.replace": "Une clé est déjà enregistrée. Saisissez-en une nouvelle pour la remplacer.",
            "apikey.info": "Collez votre clé API %@. Elle est stockée dans le fichier de réglages de l'app (lisible uniquement par votre utilisateur) et sert uniquement aux requêtes vers %@.",
            "btn.save": "Enregistrer",
            "btn.cancel": "Annuler",
            "edit.title": "Édition",
            "edit.undo": "Annuler",
            "edit.redo": "Rétablir",
            "edit.cut": "Couper",
            "edit.copy": "Copier",
            "edit.paste": "Coller",
            "edit.all": "Tout sélectionner",
            "err.noInput": "Micro indisponible (aucun périphérique d'entrée ou pas d'autorisation).",
            "err.converter": "Impossible de configurer la conversion audio.",
            "err.noCli": "whisper-cli introuvable. Installez-le : brew install whisper-cpp",
            "err.tr": "Erreur de reconnaissance : %@",
            "err.http": "Le service a renvoyé l'erreur %d : %@",
            "err.net": "Réseau indisponible : %@",
            "err.empty": "Le service a renvoyé une réponse vide.",
            "err.large": "L'enregistrement est trop long pour Gemini (limite ~7 minutes).",
            "err.nolocal": "aucun modèle local",
            "firstrun.title": "Bienvenue dans WhisperKey",
            "firstrun.text": "Choisissez la langue de l'interface.\nVous pourrez la changer à tout moment dans le menu.",
            "btn.continue": "Continuer",
        ],
        "zh": [
            "status.hold": "WhisperKey — 按住 %@",
            "status.ready": "WhisperKey — 就绪（%@）",
            "status.rec": "录音中… %@",
            "status.rec.hold": "录音中… %@ — 松开结束",
            "status.processing": "识别中…",
            "warn.rightcmd": "⚠️ 右 ⌘ 未生效 — 缺少辅助功能权限",
            "menu.axSettings": "打开辅助功能设置…",
            "menu.record": "开始录音",
            "menu.finish": "完成 — 识别并粘贴",
            "menu.cancel": "取消 (Esc)",
            "menu.copy": "拷贝：“%@”",
            "menu.engine": "识别引擎",
            "menu.model": "本地模型",
            "menu.speechLang": "语音语言",
            "menu.hotkey": "快捷键",
            "menu.mode": "录音模式",
            "mode.hold": "按住按键（按下即说）",
            "mode.toggle": "按一下开始，再按一下结束",
            "menu.autopaste": "自动粘贴到当前输入框",
            "menu.sounds": "提示音",
            "menu.modelsFolder": "打开模型文件夹",
            "menu.login": "登录时启动",
            "menu.quit": "退出",
            "menu.uiLang": "界面语言",
            "models.none": "未安装模型",
            "models.download": "下载：",
            "apikey.item": "%@ API 密钥…",
            "apikey.saved": "（已保存）",
            "speech.auto": "自动检测",
            "speech.ru": "俄语",
            "speech.en": "英语",
            "key.space": "空格",
            "key.rightcmd": "右 ⌘",
            "engine.local": "本地 (whisper.cpp)",
            "tag.fast": "快",
            "tag.accurate": "更准确",
            "tag.veryfast": "极快",
            "tag.fastacc": "又快又准",
            "tag.faster": "更快",
            "tag.top": "最高准确率",
            "tag.cheap": "便宜",
            "model.recommended": "推荐",
            "model.best": "最高质量",
            "unit.mb": "MB",
            "unit.gb": "GB",
            "hud.preparing": "正在启动麦克风…",
            "hud.rec": "录音中… %d:%02d",
            "hud.processing": "识别中…",
            "hud.processingVia": "识别中（%@）…",
            "hud.done": "完成 — 文本已在剪贴板",
            "hud.fallback": "完成（本地 — 云端不可用）",
            "hud.empty": "未识别到语音",
            "hud.fail": "识别失败",
            "alert.noModel": "没有模型",
            "alert.noModel.text": "请下载识别模型：菜单 → 本地模型 → 下载。",
            "alert.noCli": "未找到 whisper-cli",
            "alert.noCli.text": "请安装识别引擎：\nbrew install whisper-cpp",
            "alert.noMic": "无麦克风权限",
            "alert.noMic.text": "请允许访问：系统设置 → 隐私与安全性 → 麦克风 → WhisperKey。",
            "alert.recFail": "无法开始录音",
            "alert.trFail": "识别失败",
            "alert.loginFail": "无法更改登录启动项",
            "alert.axTitle": "右 ⌘ 需要权限",
            "alert.axText": "要响应右 Command 键，请授予 WhisperKey 辅助功能权限：\n系统设置 → 隐私与安全性 → 辅助功能。\n\n然后在菜单中重新选择“右 ⌘”或重启 WhisperKey。",
            "apikey.title": "%@ API 密钥",
            "apikey.replace": "已保存密钥。输入新密钥以替换。",
            "apikey.info": "粘贴你的 %@ API 密钥。它保存在应用设置文件中（仅你的用户可读），只用于向 %@ 发送请求。",
            "btn.save": "保存",
            "btn.cancel": "取消",
            "edit.title": "编辑",
            "edit.undo": "撤销",
            "edit.redo": "重做",
            "edit.cut": "剪切",
            "edit.copy": "拷贝",
            "edit.paste": "粘贴",
            "edit.all": "全选",
            "err.noInput": "麦克风不可用（无输入设备或无权限）。",
            "err.converter": "无法配置音频转换。",
            "err.noCli": "未找到 whisper-cli。请安装：brew install whisper-cpp",
            "err.tr": "识别错误：%@",
            "err.http": "服务返回错误 %d：%@",
            "err.net": "网络不可用：%@",
            "err.empty": "服务返回了空响应。",
            "err.large": "录音太长，超出 Gemini 限制（约 7 分钟）。",
            "err.nolocal": "没有本地模型",
            "firstrun.title": "欢迎使用 WhisperKey",
            "firstrun.text": "请选择界面语言。\n之后可随时在菜单中更改。",
            "btn.continue": "继续",
        ],
    ]
}
